spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICES
          uri: lb://USER-SERVICES
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICES
          uri: lb://HOTEL-SERVICES
          predicates:
            - Path=/hotels/**
        - id: RATING-SERVICES
          uri: lb://RATING-SERVICES
          predicates:
            - Path=/ratings/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084
